#!/usr/bin/perl
use strict;

sub write_top
{
	print "struct symbol {\n";
	print "\tunsigned long address;\n";
	print "\tchar type;\n";
	print "\tconst char *name;\n";
	print "};\n";
	print "\n";
        print "static const struct symbol user_symbols[] = {\n";
}

sub write_bot
{
        print "};\n";
	print "static int nsymbols = sizeof(user_symbols)/sizeof(user_symbols[0]);\n";
	print "\n";
	print "unsigned long find_vaddr(const char *name)\n";
	print "{\n";
	print "\tint i;\n";
	print "\tfor ( i=0; i<nsymbols; i++ ){\n";
	print "\t\tif ( strcmp(name,user_symbols[i].name) == 0)\n";
	print "\t\t\treturn user_symbols[i].address;\n";
	print "\t}\n";
	print "\treturn 0;\n";
	print "}\n";
}


write_top();
while ( <STDIN> ){
	chomp;
	my @nm=split;
	my $address= shift @nm;
	my $type=shift @nm;
	my $name=shift @nm;

	print "\t{\n";
	if($address=~/^[0-9a-f]+$/ ){
		print "\t .address = 0x$address,\n";
	}else{
		print "\t .address = -1,\n";
		$name = $type;
		$type = $address;
	}

	print "\t .type = '$type',\n";
	$name='"'.$name.'"';
	printf("\t .name = %s\n",$name);
        print "\t},\n";
}
write_bot()
