#!/usr/bin/perl
use strict;

sub write_top
{
	print "struct symbol {\n";
	print "\tchar            * path;\n";
	print "\tloff_t          offset ;\n";
	print "\tchar            * name;\n";
	print "};\n\n";
	print "static const struct symbol user_symbols[] = {\n";
}

sub write_bot
{
        print "};\n";
}

our $filename;
our $path;
our $objdump;
our @lines;
our $line;
$filename=$ARGV[0];
$path=`/bin/readlink -f $filename`;
chomp($path);
$objdump=`/bin/objdump -t $filename`;

@lines=split '\n', $objdump;
write_top();
foreach $line ( @lines ){
	chomp $line;
	my @nm=split /\s+/, $line;
	my $offset= shift @nm;
	my $q0=shift @nm;
	my $q1=shift @nm;
	my $sect=shift @nm;
	my $q3=shift @nm;
	my $name=shift @nm;

	if ($sect =~ m/.text/ ) {
	    print "\t{\n";

	    printf("\t .path = \"%s\",\n", $path);

	    if($offset=~/^[0-9a-f]+$/ ){
		my $val = hex($offset);
		# FIXME FIXME FIXME
		$val = $val - hex("400000")+ hex("5a");
		printf("\t .offset = (loff_t)0x%xULL,\n", $val);
	    }else{
		print "\t .offset = 0,\n";
	    }

	    printf("\t .name = \"%s\"\n", $name);
	    print "\t},\n";
	}
}
write_bot()
