
load_lib uprobes.exp

global test e_file r_file

set rdir [uprobes_mount_debugfs]

set cmd "./find_vaddr add uprobes.existing/probe7-thread.st"
catch {eval exec $cmd} vaddr 

set test "multithreaded test"
set r_file "$rdir/probe5/data"
set e_file "uprobes.existing/probe5_probe7-thread"
set module probe5
puts "running: $test"
set rc [uprobes_run_test ./runtest.sh uprobes.existing probe7-thread probe5 1 100 $vaddr verbose=0] 
if {$rc == 0} { pass $test } else { fail $test }

