
load_lib uprobes.exp

global test e_file r_file

set rdir [uprobes_mount_debugfs]

set cmd "./find_vaddr add uprobes.existing/probeme4.st"
catch {eval exec $cmd} vaddr 

set test "basic probe test"
set r_file "$rdir/probe5/data"
set e_file "uprobes.existing/probe5_probeme4"
set module probe5
puts "running: $test"
set rc [uprobes_run_test  ./runtest.sh uprobes.existing probeme4 probe5 1 5 $vaddr]
if {$rc == 0} { pass $test } else { fail $test }

