
load_lib uprobes.exp

global test e_file r_file

set rdir [uprobes_mount_debugfs]

set cmd "./find_vaddr add uprobes.existing/probeme4.st"
catch {eval exec $cmd} vaddr 

set test "test for aggregate probes 6 aggr probes 5 interations"
set r_file "$rdir/probe5ag/data"
set e_file "uprobes.existing/probe5ag_probeme4"
set module probe5ag
puts "running: $test"
set rc [uprobes_run_test  ./runtest.sh uprobes.existing probeme4 probe5ag 1 5 $vaddr]
if {$rc == 0} { pass $test } else { fail $test }
